# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: GrayMoon.Desktop
PackageVersion: 0.1.0
InstallerType: exe
InstallerSwitches:
  Silent: --silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Jandini/GrayMoon.Release/releases/download/0.1.0/GrayMoon.Desktop-stable-Setup.exe
  InstallerSha256: ECCA65E9781A1DB2B11DC3BE7D62BFE80A938C35E96FC058023AFDECE7A567E3
ManifestType: installer
ManifestVersion: 1.12.0
